### ISSUE TITLE
Feedback: ssh_tunnel

### ISSUE THREAD

**Issue by grabblies** [jonathancross/jc-docs#18]
Seems like there's a bit of complexity hiding beneath the step:

'Configure it to accept localhost RPC commands and secure via username & password.'

I would love that to be expanded out!

**Comment by jonathancross** [comment]
Cheers @grabblies -- thanks for the feedback.
I hope the updates make a bit more sense.
There really isn't much to it, just that the order in the list was funny.

**Comment by UCLA38** [comment]
> يبدو أن هناك القليل من التعقيد يختبئ تحت الخطوة:
> 
> 'قم بتكوينه لقبول أوامر RPC المحلية وتأمينها عبر اسم المستخدم وكلمة المرور.'
> 
> سأحب أن يتم توسيع ذلك!
